### PR TITLE
Show published activities in list

### PR DESCRIPTION
**Pull request by tmaybe**
The 10 most recently published activities are now shown on the front page. You can't click into them. This is the first stage of addressing #519 as described [in this comment](https://github.com/chimecms/chime/issues/519#issuecomment-138688904).

### CODE REVIEW

**Comment by tmaybe** [comment]
Ready to merge when @norrishung give his seal of approval

**Comment by norrishung** [comment]
Hey tomas, I'm not seeing any published activities locally. Can you help me figure this out when you get in?

**Comment by tmaybe** [comment]
Will do!

**Comment by tmaybe** [comment]
This should be ready to merge when tests pass.

**Pull request merged**
