### PR TITLE
Resolve GitPython stderr line count 

### LINKED ISSUE #455: fix GitPython error: len() mismatch in _get_fetch_info_from_stderr
We're seeing this a lot on production. I suspect it may be fixed by a newer version of GitPython. We're using `0.3.2.RC1` and the current release is `0.3.6`. Our issue may be the one described here:

https://github.com/gitpython-developers/GitPython/issues/301

- [ ] reproduce error on dev so we can test
- [x] try upgrading GitPython and see if that fixes it

### PR DESCRIPTION
**Pull request by migurski**
Upgraded GitPython to 1.0.1, made a few UTF-8 encoding changes throughout. [GitPython #325](https://github.com/gitpython-developers/GitPython/issues/325) suggests this might be enough. App and Process tests passed locally.

* ~~Get full test suite passing.~~
* [x] Ask for feedback on [new installation steps](https://github.com/chimecms/chime/tree/resolve-gitpython-stderr-%23455#install).

Closes #455?

### CODE REVIEW

**Comment by migurski** [comment]
I’d like to get this merged in spite of the test suite failures. After investigating, they don’t seem related to the changes made here, and I was able to get one of them to pass completely after retrying several times.

The failures [seem to stem from stubby](https://www.browserstack.com/automate/builds/79487ab1fb544f90a3d2aeaa22f188f1d1e5d7db/sessions/1218bb7a8d05d287ade456f2a433d0578b86d2a3#automate_button), and manifest immediately on login.

**Comment by migurski** [comment]
I’d love some feedback on [the tweaks to README](https://github.com/chimecms/chime/tree/resolve-gitpython-stderr-%23455#install), otherwise I think this is good to merge.

**Comment by tmaybe** [comment]
regarding the README tweaks:

1. I would add a little more context in the setup of `sample-site`, what those commands are doing, why it's important to have a bare repository and why we want to change the remote name (and how to check to verify that it's been changed).

1. I would link to the [Jekyll Install README](https://github.com/chimecms/chime/blob/resolve-gitpython-stderr-%23455/jekyll/README.md) in that step.

**Comment by tmaybe** [comment]
I reverted this merge from the command line with

`git revert -m 1 a224f50e614e75ffa4d939a66fb93065e2c6f580`

which created the commit e2f82c41bf42eba1a410af145a226814e8669362

**Comment by tmaybe** [comment]
I also clicked GitHub's `Revert` button above, which created the branch `revert-481-resolve-gitpython-stderr-#455` but nothing was done with that branch.

**Pull request merged**
