### PR TITLE
Create initial admin interface with lone publish button

### PR DESCRIPTION
**Pull request by wpietri**

### CODE REVIEW

**Comment by migurski** [comment]
Ensure the button fills the entire screen.

**Comment by tmaybe** [comment]
Publish doesn't seem like the exact right verb – maybe Synch? Because it's essentially making sure that the live site matches the most recently published activity (what's on master).

Also I'm seeing a weird bug where the exclamation point icon doesn't show up on the *Published!* flash message.

But I'm fine leaving those issues for future development of the `/admin` page. This is good to merge after rebase and when Travis tests pass.

**Comment by wpietri** [comment]
Yeah, I agree that "publish" is confusing, in that we use it both to mean "commit a users changes to master" and "render what's in master to the public web site". SInce they're always supposed to happen at the same time, perhaps the real solution is to make this button unnecessary.

**Comment by phae** [comment]
Where is this admin interface? Where did this ticket come from?

**Comment by wpietri** [comment]
The "interface" is at /admin. Twice in the last week we've needed to be able to re-publish the public-facing web site. Once because we wanted to update the templates, and once because a disk filled up, causing the publishing operation to be incomplete. Since I needed some way to force a re-publish (that is, taking whatever's in master and building a fresh website from it), I made a button to do it.

**Pull request merged**
