### PR TITLE
Save on preview

### LINKED ISSUE #181: Hitting "preview" should also do a save action

### LINKED ISSUE #321: Internal error when saving a new article
Tried to save a [new article](http://springfield-admin.chimecms.org/tree/74b5d90/save/categories/parks-recreation/aquatics/mount-splashmore/index.markdown), got an internal error.

This is the likely corresponding error via SNS:

```
2015-07-02 21:39:47,241 - chime.view_functions - ERROR - Out of date SHA: c1fcb05d39fbe80287ee229bd04761254030dcbd
Traceback (most recent call last):
 File "/home/ubuntu/chime/chime/view_functions.py", line 432, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 464, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 520, in decorated_function
   response = route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/views.py", line 775, in branch_save
   raise Exception('Out of date SHA: %s' % request.form.get('hexsha'))
Exception: Out of date SHA: c1fcb05d39fbe80287ee229bd04761254030dcbd

Request info:
<Request 'http://springfield-admin.chimecms.org/tree/74b5d90/save/categories/parks-recreation/aquatics/mount-splashmore/index.markdown' [POST]>
```

### PR DESCRIPTION
**Pull request by migurski**
This now saves and redirects.

* [x] Add a test.
* [x] Fix #321 before merging

Closes #181.

### CODE REVIEW

**Comment by migurski** [comment]
I believe this to be ready to merge—the test failures look like Browserstack badness?

**Comment by tmaybe** [comment]
I tried this out locally. If I preview and return to the page to make further edits, I hit bug #321 when I try to preview again or save. Because preview saved, the hexsha embedded in the form is no longer current. Okay to merge anyway?

**Comment by migurski** [comment]
Rebased, ready for review.

**Comment by tmaybe** [comment]
let's fix #321 before we merge this

**Comment by tmaybe** [comment]
also, acceptance tests are failing because it's looking for the old-style preview button (and assumes that preview opens a new window)

**Comment by tmaybe** [comment]
Acceptance tests are failing on **Windows 7 IE 8**: after preview, the test loads the front page/activity list directly (meaning, without clicking on a link) and the browser loads that page from cache. The page in cache doesn't list the activity that the test created, so the test fails when looking for the activity to delete it. If you reloading the page, or load it in the first place by clicking a link on another page in the site, the page is loaded fresh and the activity is visible.

**Comment by tmaybe** [comment]
I'm not sure why the change to the way preview works would have this affect?

**Comment by tmaybe** [comment]
ready to merge when #321 is fixed.

**Comment by migurski** [comment]
Rebased again with code from merged #321. Tests pass locally.

**Comment by migurski** [comment]
:+1:

**Pull request merged**
