### PR TITLE
SNS logging of errors

### PR DESCRIPTION
**Pull request by wpietri**
This code adds support for production logging of SNS errors. To activate it, set SNS_ALERTS_TOPIC to an AWS ARN that accepts public posts.

### CODE REVIEW

**Comment by migurski** [comment]
Making some slow progress on normalizing error reporting here.

1. Our mangling of `sys.path` was incorrect; prepending causes the tests to correctly use local `chime` instead of system `chime`: https://github.com/chimecms/chime/commit/326b7d5b2
2. I’m getting application errors more reliably disentangled from Flask errors by renaming the default app logger to _chime-flask_ and capturing all route errors to the _chime_ logger: https://github.com/chimecms/chime/commit/417ca58e2

**Comment by migurski** [comment]
Looking at `ChimeFileLoggingHandler` thinking there might be something we could do here with explicitly passing in a filename, instead of calculating something from `WORK_PATH` or `/var/log`. It’s doing a tiny bit too much.

**Comment by wpietri** [comment]
Legitimate concern. Pulling only one out seemed weird, which is why I left it. So perhaps we pass in a list of possible directories in preference order?

**Comment by migurski** [comment]
List of directories in order sounds good!

**Pull request merged**
