### PR TITLE
Upgraded GitPython to 1.0.1

### LINKED ISSUE #455: fix GitPython error: len() mismatch in _get_fetch_info_from_stderr
We're seeing this a lot on production. I suspect it may be fixed by a newer version of GitPython. We're using `0.3.2.RC1` and the current release is `0.3.6`. Our issue may be the one described here:

https://github.com/gitpython-developers/GitPython/issues/301

- [ ] reproduce error on dev so we can test
- [x] try upgrading GitPython and see if that fixes it

### PR DESCRIPTION
**Pull request by migurski**
Reprise of #481, possibly closes #455.

### CODE REVIEW

**Comment by wpietri** [comment]
This failed once on travis, and also isn't working right on my machine. I'm investigating.

**Comment by tmaybe** [comment]
I think this is ready, but would appreciate a sanity check on my changes.

The change in af54403 closes #493

**Comment by wpietri** [comment]
I like it and think it's a step forward. I think we really need to figure out some consistent place to handle encoding, though. Sprinkling UTF calls in many places is just asking for bugs; it's too easy to forget. Would switching to Python 3 help us here?

**Comment by tmaybe** [comment]
Yeah, I think these changes reflect the new version of GitPython acting in a Python 3 manner, so all reads/writes that are brokered by GitPython no longer need us to manually indicate encoding.

I'm open to porting to Python 3.

**Comment by migurski** [comment]
I am also open to porting. I propose an interim approach of adding Python 3 to our testing matrix so we have confidence that the code works there before we modify our various deployment things. I’ve found that testing in 3.x alone can introduce the benefits of 3.

**Pull request merged**
